// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWntt6YW5qaeYZ23jGlH5-oembTWQO0T8',
    appId: '1:1018404075469:ios:4c77122a67849ae8043684',
    messagingSenderId: '1018404075469',
    projectId: 'fruits-hub-ac432',
    storageBucket: 'fruits-hub-ac432.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWKDjpcUKFUIFB5xPQRZv0JG4-8S0BHFo',
    appId: '1:1018404075469:web:6c32200eef582c9b043684',
    messagingSenderId: '1018404075469',
    projectId: 'fruits-hub-ac432',
    authDomain: 'fruits-hub-ac432.firebaseapp.com',
    storageBucket: 'fruits-hub-ac432.firebasestorage.app',
    measurementId: 'G-10K5H3NGZF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWKDjpcUKFUIFB5xPQRZv0JG4-8S0BHFo',
    appId: '1:1018404075469:web:6c32200eef582c9b043684',
    messagingSenderId: '1018404075469',
    projectId: 'fruits-hub-ac432',
    authDomain: 'fruits-hub-ac432.firebaseapp.com',
    storageBucket: 'fruits-hub-ac432.firebasestorage.app',
    measurementId: 'G-10K5H3NGZF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWntt6YW5qaeYZ23jGlH5-oembTWQO0T8',
    appId: '1:1018404075469:ios:4c77122a67849ae8043684',
    messagingSenderId: '1018404075469',
    projectId: 'fruits-hub-ac432',
    storageBucket: 'fruits-hub-ac432.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aX_Qt-MMIExQp1hGXWZldUm4dd7nim4',
    appId: '1:1018404075469:android:aba7f1da8f90c371043684',
    messagingSenderId: '1018404075469',
    projectId: 'fruits-hub-ac432',
    storageBucket: 'fruits-hub-ac432.firebasestorage.app',
  );
}
